apiVersion: v1
kind: Service
metadata:
  name: ${INSTANCE}
  labels:
    app.kubernetes.io/name: springboot-wmq-sender-listener
    app.kubernetes.io/instance: ${INSTANCE}
spec:
  selector:
    app.kubernetes.io/name: springboot-wmq-sender-listener
    app.kubernetes.io/instance: ${INSTANCE}
  ports:
  - port: 8080